# Generated by Django 3.0.2 on 2020-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naiss', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
