# Generated by Django 3.0.2 on 2020-01-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='dateDebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='dateFin',
            field=models.DateField(),
        ),
    ]
