# Generated by Django 3.0.2 on 2020-01-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_cite_nbr_chmbr_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserv',
            name='idChambre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.Chambre'),
            preserve_default=False,
        ),
    ]
