# Generated by Django 3.0.2 on 2020-01-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20200109_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='chambre',
        ),
        migrations.AddField(
            model_name='chambre',
            name='categori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.Categorie'),
            preserve_default=False,
        ),
    ]
