# Generated by Django 3.0.2 on 2020-01-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20200109_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cloturer',
            field=models.BooleanField(default=False),
        ),
    ]
