# Generated by Django 3.0.2 on 2020-01-09 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_categorie_cloturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='IdClient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reservation.client'),
            preserve_default=False,
        ),
    ]
