# Generated by Django 3.0.2 on 2020-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
