# Generated by Django 3.0.2 on 2020-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200108_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
