# Generated by Django 3.0.2 on 2020-01-08 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200108_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(auto_now_add=True)),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.client')),
            ],
        ),
    ]
