# Generated by Django 3.0.2 on 2020-01-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200108_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='nbr_chmbr_dispo',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
