# Generated by Django 3.0.2 on 2020-01-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200109_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='categori',
            new_name='categorie',
        ),
    ]
